load("E:\\Office Account\\GitHub\\texreg\\data.RData")
library(texreg) #加载包
screenreg(list(model1,model2,model3,model4),
          stars = c(0.01,0.05,0.1),
          digits = 4,
          #star.symbol = "@",
          single.row = F,
          #custom.model.names = c("M1","M2","M3","M4"),
          custom.coef.names = c("edges","gwesp","homogeneity","tech_proximnity","inst_proximity","geo_proximity"), 
          custom.gof.rows = list("method"=c("MCMC","MCMC","MCMC","MCMC"),
                                 "N" = c("?","?","?","?")),
          #custom.note = c("注:*** p < 0.01; ** p < 0.05; * p < 0.1,括号内为标准误"),
          leading.zero = F,
          #ci.force = c(T,T,T,T),
          group = list("内生属性" = 1:2,"节点属性" = 3,"网络协变量" = 4:6))
htmlreg(list(model1,model2,model3,model4),
          stars = c(0.01,0.05,0.1),
          digits = 4,
          #star.symbol = "@",
          single.row = F,
          #custom.model.names = c("M1","M2","M3","M4"),
          custom.coef.names = c("edges","gwesp","homogeneity","tech_proximnity","inst_proximity","geo_proximity"), 
          custom.gof.rows = list("method"=c("MCMC","MCMC","MCMC","MCMC"),
                                 "N" = c("?","?","?","?")),
          custom.note = c("注:*** p < 0.01; ** p < 0.05; * p < 0.1,括号内为标准误"),
          leading.zero = F,
          #ci.force = c(T,T,T,T),
          group = list("内生属性" = 1:2,"节点属性" = 3,"网络协变量" = 4:6),
          file = "result.html")

wordreg(list(model1,model2,model3,model4),
        stars = c(0.01,0.05,0.1),
        digits = 4,
        #star.symbol = "@",
        single.row = F,
        #custom.model.names = c("M1","M2","M3","M4"),
        custom.coef.names = c("edges","gwesp","homogeneity","tech_proximnity","inst_proximity","geo_proximity"), 
        custom.gof.rows = list("method"=c("MCMC","MCMC","MCMC","MCMC"),
                               "N" = c("?","?","?","?")),
        #custom.note = c("注:*** p < 0.01; ** p < 0.05; * p < 0.1,括号内为标准误"),
        leading.zero = F,
        #ci.force = c(T,T,T,T),
        group = list("内生属性" = 1:2,"节点属性" = 3,"网络协变量" = 4:6),
        file = "result.doc")

